const IS_LOADING = "IS_LOADING";
const IS_ERROR = "IS_ERROR";
const STORE_DATA = "STORE_DATA";

const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING";
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR";
const CURRENT_PRODUCT_STORE_DATA = "CURRENT_PRODUCT_STORE_DATA";

export {
  IS_LOADING,
  STORE_DATA,
  IS_ERROR,
  CURRENT_PRODUCT_LOADING,
  CURRENT_PRODUCT_STORE_DATA,
  CURRENT_PRODUCT_ERROR,
};
